---
- name: make systemd/system directory if nonexistent
  file:
    force=yes
    recurse=yes
    state=directory
    path=/usr/lib/systemd/system

- name: move unit file to place
  template:
    src="domains.j2"
    dest="/usr/lib/systemd/system/domains.service"
    owner="{{ user.name }}"

- name: enable docker container
  service:
    name=domains
    enabled=yes
    state=reloaded
